import { StyleSheet, Platform, Dimensions, StatusBar } from 'react-native';

const { width, height } = Dimensions.get('window');
const isSmallDevice = width < 375;

// Color palette
const colors = {
  primary: '#3366FF',
  primaryDark: '#2952CC',
  primaryLight: '#EBF0FF',
  secondary: '#FF9800',
  background: '#F7F9FC',
  white: '#FFFFFF',
  text: '#222B45',
  textSecondary: '#8F9BB3',
  border: '#E4E9F2',
  success: '#00E096',
  danger: '#FF3D71',
  shadow: 'rgba(0, 0, 0, 0.1)',
  gradient1: '#3366FF',
  gradient2: '#00CCFF',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight || 0,
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  glassContainer: {
    width: width * 0.92,
    maxWidth: 500,
    padding: 24,
    backgroundColor: colors.white,
    borderRadius: 24,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
    marginTop: 16,
  },
  searchButton: {
    backgroundColor: colors.primary,
    padding: isSmallDevice ? 14 : 16,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 24,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  searchButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: isSmallDevice ? 15 : 16,
    letterSpacing: 0.5,
  },
  searchButtonDisabled: {
    backgroundColor: colors.textSecondary,
    shadowOpacity: 0.1,
  },
  titleContainer: {
    alignItems: 'center',
    width: '100%',
    marginBottom: isSmallDevice ? 20 : 30,
    paddingTop: 10,
  },
  appTitle: {
    fontSize: isSmallDevice ? 32 : 38,
    fontWeight: 'bold',
    color: colors.primary,
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    marginBottom: 8,
  },
  title: {
    fontSize: isSmallDevice ? 14 : 16,
    color: colors.textSecondary,
    marginBottom: 8,
    fontStyle: 'italic',
    letterSpacing: 0.5,
  },
  titleText: {
    fontSize: isSmallDevice ? 24 : 28,
    fontWeight: '600',
    color: colors.primary,
    marginBottom: 24,
  },
  inputContainer: {
    gap: 20,
  },
  searchResults: {
    backgroundColor: colors.white,
    borderRadius: 16,
    marginTop: -12,
    marginBottom: 10,
    paddingVertical: 8,
    maxHeight: 200,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    zIndex: 2,
  },
  searchResultItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchResultText: {
    fontSize: 14,
    color: colors.text,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: isSmallDevice ? 14 : 16,
    borderRadius: 16,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  inputWrapperFocused: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  input: {
    flex: 1,
    fontSize: isSmallDevice ? 14 : 16,
    color: colors.text,
  },
  clearButton: {
    fontSize: 20,
    color: colors.textSecondary,
    padding: 6,
  },
  locationButton: {
    fontSize: 20,
    padding: 6,
    color: colors.primary,
  },
  busRoutesContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.background,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  busRoutesHeader: {
    padding: 16,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  busRoutesTitle: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: '600',
    color: colors.text,
    marginLeft: 16,
  },
  busRoutesList: {
    padding: 16,
  },
  backButton: {
    padding: 8,
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
  },
  backButtonText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '500',
  },
  busRouteContainer: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  busHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  busNumber: {
    fontSize: isSmallDevice ? 16 : 18,
    fontWeight: '700',
    color: colors.primary,
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    overflow: 'hidden',
  },
  timeContainer: {
    marginBottom: 12,
    backgroundColor: colors.primaryLight,
    padding: 12,
    borderRadius: 12,
  },
  timeText: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 4,
  },
  routeInfo: {
    marginTop: 12,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  routeText: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 6,
    lineHeight: 20,
  },
  statusText: {
    fontSize: 14,
    color: colors.success,
    fontWeight: '600',
  },
  statusTextBusy: {
    color: colors.secondary,
  },
  statusTextCrowded: {
    color: colors.danger,
  },
  noRoutesText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 16,
  },
  locationIcon: {
    marginRight: 8,
    color: colors.primary,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    width: '100%',
    marginVertical: 8,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  adContainer: {
    backgroundColor: "beige",
    padding: 16,
    margin: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  adTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
  },
  adImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    marginBottom: 8,
  },
  adText: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 8,
  },
  adCTA: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#d32f2f",
  },
});